### PR TITLE
Ruby 2.4 upgrade

### PR DESCRIPTION
**Pull request by jonworek**
## Problem
Ruby and other dependencies have fallen out of date.

## Solution
In the spirit of upgrading other internal Stitch Fix apps, I felt it appropriate to bring along the merch calendar gem into the modern ruby world.

One notable change is that I had to drop support for Ruby 1.9.3.  I maybe could've found a way to support it if I really wanted to be creative, but I felt that the cost likely outweighed the benefit.

The code changes you see were done to eliminate deprecation warnings caused by the various dependency updates.

## Deployment checklist

- [ ] bump gem version to (maybe?) 1.0

It's probably about time we took this gem out of "prerelease" status.  We've put a lot of work into it recently, and it should be pretty stable.

### CODE REVIEW

**Comment by davetron5000** [comment]
Should we update the build matrix for 2.3.5 and 2.4.2?

**Comment by jonworek** [comment]
@davetron5000 when I looked at https://www.ruby-lang.org/en/downloads/releases/

I saw that 2.4.1 and 2.3.4 were the latest stable releases.

Where is your intel coming from?

**Comment by davetron5000** [comment]
https://www.ruby-lang.org/en/news/

Looks like they have not updated the download page, but these versions were released today.

**Comment by jonworek** [comment]
@davetron5000 thanks for the info.  I'll give it a shot, but travisci doesn't have them reflected on their "supported versions" page yet.  http://rubies.travis-ci.org/

🤞

**Comment by jonworek** [comment]
2.3.5 was good, but travisci blew up on 2.4.2.  We can save 2.4.2 for another day.

**Comment by jonworek** [comment]
I did also discover that adding `ruby-head` to the list of rubies should presumably always make it build against whatever is the most recent ruby.  That should future-proof us.

**Comment by jonworek** [comment]
>Hey @jonworek! Since you're changing the params from Fixnum to Integer, did you want to do it for the StitchFixFiscalCalendar, and the MerchWeek classes?

@chylauSF good callout!  I'll take care of it.  Thanks!

**Pull request merged**
